// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr8RJ_x7slHgVUMNgjaSG4kLSjogYD0kQ',
    appId: '1:673863646937:web:3f945cd79a7bd5058288c8',
    messagingSenderId: '673863646937',
    projectId: 'cashierapp-20917',
    authDomain: 'cashierapp-20917.firebaseapp.com',
    databaseURL: 'https://cashierapp-20917-default-rtdb.firebaseio.com',
    storageBucket: 'cashierapp-20917.appspot.com',
    measurementId: 'G-VSPM4GD562',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2cDmsH0Lsk8zzNO2YETD80eySPX604AI',
    appId: '1:673863646937:android:df23f76cf17727e28288c8',
    messagingSenderId: '673863646937',
    projectId: 'cashierapp-20917',
    databaseURL: 'https://cashierapp-20917-default-rtdb.firebaseio.com',
    storageBucket: 'cashierapp-20917.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQy7JO6TYNCC5kcu97joMCRG9lRYCkRL4',
    appId: '1:673863646937:ios:94a94f8f206911538288c8',
    messagingSenderId: '673863646937',
    projectId: 'cashierapp-20917',
    databaseURL: 'https://cashierapp-20917-default-rtdb.firebaseio.com',
    storageBucket: 'cashierapp-20917.appspot.com',
    iosBundleId: 'com.example.latihanuts2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQy7JO6TYNCC5kcu97joMCRG9lRYCkRL4',
    appId: '1:673863646937:ios:1526248b23747c4f8288c8',
    messagingSenderId: '673863646937',
    projectId: 'cashierapp-20917',
    databaseURL: 'https://cashierapp-20917-default-rtdb.firebaseio.com',
    storageBucket: 'cashierapp-20917.appspot.com',
    iosBundleId: 'com.example.latihanuts2.RunnerTests',
  );
}
