// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyuzbWv8Z2CLJiYZbbkO0Qqb8Ud-LrABE',
    appId: '1:332804507206:web:c4b6110c80ccf17162ec47',
    messagingSenderId: '332804507206',
    projectId: 'dbnotes-86d2c',
    authDomain: 'dbnotes-86d2c.firebaseapp.com',
    databaseURL: 'https://dbnotes-86d2c-default-rtdb.firebaseio.com',
    storageBucket: 'dbnotes-86d2c.appspot.com',
    measurementId: 'G-L0ZMWJ6MQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFzbLyAFXJNPQNShcbHqi749jgOh9J-yo',
    appId: '1:332804507206:android:d7193dd4a86cbf2162ec47',
    messagingSenderId: '332804507206',
    projectId: 'dbnotes-86d2c',
    databaseURL: 'https://dbnotes-86d2c-default-rtdb.firebaseio.com',
    storageBucket: 'dbnotes-86d2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5qeurT0OwlyVT411Nhv8gFtQAYtTBd-o',
    appId: '1:332804507206:ios:97eeabdfbef84e8962ec47',
    messagingSenderId: '332804507206',
    projectId: 'dbnotes-86d2c',
    databaseURL: 'https://dbnotes-86d2c-default-rtdb.firebaseio.com',
    storageBucket: 'dbnotes-86d2c.appspot.com',
    iosBundleId: 'com.example.notesApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5qeurT0OwlyVT411Nhv8gFtQAYtTBd-o',
    appId: '1:332804507206:ios:90e3f8907890ed3162ec47',
    messagingSenderId: '332804507206',
    projectId: 'dbnotes-86d2c',
    databaseURL: 'https://dbnotes-86d2c-default-rtdb.firebaseio.com',
    storageBucket: 'dbnotes-86d2c.appspot.com',
    iosBundleId: 'com.example.notesApps.RunnerTests',
  );
}
